# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "left-right-tiles"
  description: Information tiles on one side (with icons), image on the other, on left a heading.
  icon: grid_view
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  section_background_color: '#F8F9FA'
  subtitle: 
  text: 
  image_path: /uploads/unsplash_axE5o1Xh7_Q.png
  image_alt: 
  icon1_path: /uploads/Icon-Light-hand-plant 1.png
  title1: 
  content1: 
  icon2_path: /uploads/Icon-Light-plants-growth 1.png
  title2: 
  content2: 
  icon3_path: /uploads/Icon-Light-world-certified-tick 1.png
  title3: 
  content3: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  section_background_color: '#F8F9FA'
  subtitle: Why Forest Positive matters
  text: >-
      Reducing print waste isn’t enough anymore. Turn your printing’s impact
      around from a negative environmental footprint to a positive force for
      ecological renewal by becoming Forest Positive.
  image_path: /uploads/unsplash_axE5o1Xh7_Q.png
  image_alt: Logging area
  icon1_path: /uploads/Icon-Light-hand-plant 1.png
  title1: Deforestation
  content1: 20% of current greenhouse gases are due to tropical forest destruction
  icon2_path: /uploads/Icon-Light-plants-growth 1.png
  title2: Print Footprint
  content2: >-
      30% of trees cut down are used for paper processing, essential business
      printing needs to do more than minimize paper waste
  icon3_path: /uploads/Icon-Light-world-certified-tick 1.png
  title3: Climate change
  content3: >-
      One mature tree absorbs more than 48 pounds of carbon dioxide each year,
      that's enough oxygen to keep a human breathing for 2 years!

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  section_background_color:
    type: select
    options:
      values:
        - "#F8F9FA"
        - "#FFFFFF"
