# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "image-cards"
  description:
  icon: amp_stories
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
section_background_color: '#F8F9FA'
    black_heading: 
    text: 
    cards: 
    - image: /uploads/unsplash_gHho4FE4Ga0.png
      icon: /uploads/image 16.png
      title: 
      summary: 
      link: 
    - image: /uploads/Background.png
      icon: /uploads/image 16-2.png
      title: 
      summary: 
      link: 
    - image: /uploads/unsplash_19SC2oaVZW0.png
      icon: /uploads/image 16-3.png
      title: 
      summary: 
      link: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  section_background_color: '#F8F9FA'
  black_heading: Who does the planting?
  text: >-
    Meet some of the amazing non-profit and NGOs on the field who are planting
    trees on your behalf.
  cards: 
    - image: /uploads/unsplash_gHho4FE4Ga0.png
      icon: /uploads/image 16.png
      title: PrintReleaf
      summary: >-
        A certification system and software platform for automated global
        reforestation
       link: /
     - image: /uploads/Background.png
       icon: /uploads/image 16-2.png
       title: One Tree Planted
       summary: >-
        Announced targets for reducing carbon emissions and climate partnerships
        to work on ocean conservation and forest restoration
      link: /
    - image: /uploads/unsplash_19SC2oaVZW0.png
      icon: /uploads/image 16-3.png
      title: Konica Minolta
      summary: >-
        Enabling carbon neutrality program
      link: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  section_background_color:
    comment: Make the background colours alternate with the previous section.
    type: select
    options:
      values:
        - "#F8F9FA"
        - "#FFFFFF"
