# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "image-cards"
  description:
  icon: amp_stories
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  section_background_color: '#F8F9FA'
  black_heading: Who does the planting?
  text: 
  image1: /uploads/unsplash_gHho4FE4Ga0.png
  icon1: /uploads/image 16.png
  title1: 
  summary1: 
  link1: /
  image2: /uploads/Background.png
  icon2: /uploads/image 16-2.png
  title2: 
  summary2: 
  link2: /
  image3: /uploads/unsplash_19SC2oaVZW0.png
  icon3: /uploads/image 16-3.png
  title3: 
  summary3: 
  link3: /

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  section_background_color: '#F8F9FA'
  black_heading: Who does the planting?
  text: >-
    Meet some of the amazing non-profit and NGOs on the field who are planting
    trees on your behalf.
  image1: /uploads/unsplash_gHho4FE4Ga0.png
  icon1: /uploads/image 16.png
  title1: PrintReleaf
  summary1: >-
    A certification system and software platform for automated global
    reforestation
  link1: /
  image2: /uploads/Background.png
  icon2: /uploads/image 16-2.png
  title2: One Tree Planted
  summary2: >-
    Announced targets for reducing carbon emissions and climate partnerships
    to work on ocean conservation and forest restoration
  link2: /
  image3: /uploads/unsplash_19SC2oaVZW0.png
  icon3: /uploads/image 16-3.png
  title3: Konica Minolta
  summary3: Enabling carbon neutrality program
  link3: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  section_background_color:
    comment: Make the background colours alternate with the previous section.
    type: select
    options:
      values:
        - "#F8F9FA"
        - "#FFFFFF"
