# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "hero"
  description: Hero section with an image for the background, logo, heading and button.
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: /uploads/lukasz-szmigiel-2ShvY8Lf6l0-unsplash.jpg
  logo_path: /uploads/PaperCut-Grows-Logo-FA21-RGB 1.svg
  subtitle: Grow your sustainability story with Forest Positive printing
  button: Get Papercut grows

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_image: /uploads/lukasz-szmigiel-2ShvY8Lf6l0-unsplash.jpg
  logo_path: /uploads/PaperCut-Grows-Logo-FA21-RGB 1.svg
  subtitle: Grow your sustainability story with Forest Positive printing
  button: Get Papercut grows


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
