# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "image-left-color-background"
  description: Image on the left side, text on the right. A background colour behind the image and text, button.
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  section_background_color: "#FFFFFF"
  heading: 
  text: 
  button_text: 
  image_path: /uploads/M2112-005_PaperCut-Grows-Summit-FAQs-FA 2.png
  image_alt: 
  image_background_color: "#F3FAF4"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  section_background_color: "#FFFFFF"
  heading: How to get PaperCut Grows
  text: Getting PaperCut Grows is easy. Just get in touch with one of our Authorised Partners and they will happily get you ready.
  button_text: Find out how
  image_path: /uploads/M2112-005_PaperCut-Grows-Summit-FAQs-FA 2.png
  image_alt: People planting trees
  image_background_color: "#F3FAF4"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
