# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "image-card"
  description:
  icon: amp_stories
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: /uploads/unsplash_gHho4FE4Ga0.png
  icon: /uploads/image 16.png
  title: PrintReleaf
  summary: >-
    A certification system and software platform for automated global
    reforestation
  link: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
