# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "video-center"
  description: Video area with image background. Heading and subheading then background image with a video on top.
  icon: play_arrow
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  section_background_color: "#FFFFFF"
  black_text: 
  text: 
  background_image_left:  /uploads/image 15.png
  background_image_right: /uploads/image 14.png
  video: /uploads/Screen Shot 2022-03-16 at 1.36 1.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  section_background_color: "#FFFFFF"
  black_text: Forest Positive printing with PaperCut Grows
  text: Just reducing waste isn’t enough anymore. Turn your printing’s impact around by becoming Forest Positive.
  background_image_left:  /uploads/image 15.png
  background_image_right: /uploads/image 14.png
  video: /uploads/Screen Shot 2022-03-16 at 1.36 1.png

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  section_background_color:
    comment: Make the background colours alternate with the previous section.
    type: select
    options:
      values:
        - "#F8F9FA"
        - "#FFFFFF"
