# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "call-to-action"
  description: Call to action section with two buttons.
  icon: call_to_action
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  section_background: "#26A726"
  heading: Ready to get started?
  text: Compare our products or dive a little deeper into product solutions.
  white_button: Compare our products
  green_button: Try for free

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  section_background: "#26A726"
  heading: Ready to get started?
  text: Compare our products or dive a little deeper into product solutions.
  white_button: Compare our products
  green_button: Try for free

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
